// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Fx4sVKaGYnlqjYpAs69u7pAs8drBxdE',
    appId: '1:393883643191:web:53af5300727d4f459abeb2',
    messagingSenderId: '393883643191',
    projectId: 'nadia-elsaih',
    authDomain: 'nadia-elsaih.firebaseapp.com',
    databaseURL: 'https://nadia-elsaih-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nadia-elsaih.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtcu8JZ94UwhSryDwQR52uo7YHYovTV-8',
    appId: '1:393883643191:android:4e4ad8b330d862689abeb2',
    messagingSenderId: '393883643191',
    projectId: 'nadia-elsaih',
    databaseURL: 'https://nadia-elsaih-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nadia-elsaih.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfB3Lu1ZdHMtpex3Gi9PPOcOMI-853Mko',
    appId: '1:393883643191:ios:6539b7bc9fbe36969abeb2',
    messagingSenderId: '393883643191',
    projectId: 'nadia-elsaih',
    databaseURL: 'https://nadia-elsaih-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nadia-elsaih.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
