// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLn_SwL1lTt-Qi9r_8ZRMWXQgjCCn249g',
    appId: '1:956029703593:web:1110a0db02f37fa16560b8',
    messagingSenderId: '956029703593',
    projectId: 'edu-nadia',
    authDomain: 'edu-nadia.firebaseapp.com',
    storageBucket: 'edu-nadia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTrtroNqHEaNqwshm0ytBwJc31EYOypo8',
    appId: '1:956029703593:android:696f6a45563a62a16560b8',
    messagingSenderId: '956029703593',
    projectId: 'edu-nadia',
    storageBucket: 'edu-nadia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC1lXJdl4ls4ZIa-oHLATfhuXBh56Ourc',
    appId: '1:956029703593:ios:c898e7803afe1d636560b8',
    messagingSenderId: '956029703593',
    projectId: 'edu-nadia',
    storageBucket: 'edu-nadia.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
