// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjkGpvyjhcMOly2S8l3FknukkLER_9rwI',
    appId: '1:801769266716:web:9a654fb7aa40f9d9fec9d9',
    messagingSenderId: '801769266716',
    projectId: 'edu-vista-nadia',
    authDomain: 'edu-vista-nadia.firebaseapp.com',
    storageBucket: 'edu-vista-nadia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCmJCuXg_a9oOKflc6BCVhfDZkbglLq60',
    appId: '1:801769266716:android:729282dee7e6b612fec9d9',
    messagingSenderId: '801769266716',
    projectId: 'edu-vista-nadia',
    storageBucket: 'edu-vista-nadia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkZJgda1hX9RgzXGNGceMWxoBqhu3TR8U',
    appId: '1:801769266716:ios:8758e01e5cb06d2cfec9d9',
    messagingSenderId: '801769266716',
    projectId: 'edu-vista-nadia',
    storageBucket: 'edu-vista-nadia.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
